# Broadcasting & Operaciones

In [20]:
import numpy as np

In [18]:
prices = np.array([100,200,300])
discount = np.array([0.9])
discount_prices = prices * discount
print(discount_prices)

[ 90. 180. 270.]


In [19]:
prices = np.random.randint(100,500, size=(3,3))
discount = np.array([10,20,30])
discount_prices = prices + discount
print(prices)
print(discount_prices)

[[242 454 181]
 [385 125 347]
 [255 198 370]]
[[252 474 211]
 [395 145 377]
 [265 218 400]]


In [21]:
array = np.array([1,2,3,4,5])
print(np.all(array > 9))

False


In [22]:
print(np.any(array > 0))

True


In [23]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
concatenated_a = np.concatenate((array_a, array_a))
concatenated_ab = np.concatenate((array_a, array_b))
print(concatenated_a)
print(concatenated_ab)

[1 2 3 1 2 3]
[1 2 3 4 5 6]


In [24]:
stacked_v = np.vstack((array_a, array_b))
print(stacked_v)

[[1 2 3]
 [4 5 6]]


In [25]:
satecked_h = np.hstack((array_a, array_b))
print(satecked_h)

[1 2 3 4 5 6]


In [29]:
array_c = np.arange(1,10)
split_array = np.split(array,5)
print(array)
print(split_array)

[1 2 3 4 5]
[array([1]), array([2]), array([3]), array([4]), array([5])]
