# 8 Caso Práctico

In [39]:
import numpy as np

# Paso 1: Crear arrays con datos de ventas mensuales
meses = np.array(['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'])
ventas_A = np.array([150, 200, 250, 300, 220, 210, 180, 190, 230, 240, 280, 300])
ventas_B = np.array([180, 210, 230, 250, 270, 260, 240, 250, 270, 290, 310, 330])
ventas_C = np.array([200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420])

In [40]:
# Paso 2: Transformaciones básicas con NumPy
# Estadísticas básicas
media_A = np.mean(ventas_A)
suma_A = np.sum(ventas_A)
media_B = np.mean(ventas_B)
suma_B = np.sum(ventas_B)
media_C = np.mean(ventas_C)
suma_C = np.sum(ventas_C)

print(f"Media de ventas Producto A: {media_A}")
print(f"Suma de ventas Producto A: {suma_A}")
print(f"Media de ventas Producto B: {media_B}")
print(f"Suma de ventas Producto B: {suma_B}")
print(f"Media de ventas Producto C: {media_C}")
print(f"Suma de ventas Producto C: {suma_C}")

Media de ventas Producto A: 229.16666666666666
Suma de ventas Producto A: 2750
Media de ventas Producto B: 257.5
Suma de ventas Producto B: 3090
Media de ventas Producto C: 310.0
Suma de ventas Producto C: 3720


In [41]:
# Paso 3: Manipulación y análisis de datos
# Calcular el total de ventas por mes
total_ventas_por_mes = ventas_A + ventas_B + ventas_C

# Calcular el promedio de ventas por producto
promedio_ventas_productos = np.array([media_A, media_B, media_C])

# Identificar el mes con mayor y menor ventas
mes_mayor_ventas = meses[np.argmax(total_ventas_por_mes)]
mes_menor_ventas = meses[np.argmin(total_ventas_por_mes)]

print("Total de ventas por mes:", total_ventas_por_mes)
print("Promedio de ventas por producto:", promedio_ventas_productos)
print(f"Mes con mayor ventas: {mes_mayor_ventas}")
print(f"Mes con menor ventas: {mes_menor_ventas}")

Total de ventas por mes: [ 530  630  720  810  770  770  740  780  860  910  990 1050]
Promedio de ventas por producto: [229.16666667 257.5        310.        ]
Mes con mayor ventas: Diciembre
Mes con menor ventas: Enero


In [42]:
# Paso 4: Operaciones avanzadas con NumPy
# Reshape y Transposición
ventas_matrix = np.array([ventas_A, ventas_B, ventas_C])
ventas_reshaped = ventas_matrix.reshape(3, 4, 3)
ventas_transposed = ventas_matrix.T

print("Ventas Matrix:\n", ventas_matrix)
print("Ventas Reshaped (3, 4, 3):\n", ventas_reshaped)
print("Ventas Transposed:\n", ventas_transposed)

# Invertir arrays y aplanar matrices
ventas_inverted = ventas_matrix[:, ::-1]
ventas_flattened = ventas_matrix.flatten()

print("Ventas Invertidas:\n", ventas_inverted)
print("Ventas Aplanadas:\n", ventas_flattened)

Ventas Matrix:
 [[150 200 250 300 220 210 180 190 230 240 280 300]
 [180 210 230 250 270 260 240 250 270 290 310 330]
 [200 220 240 260 280 300 320 340 360 380 400 420]]
Ventas Reshaped (3, 4, 3):
 [[[150 200 250]
  [300 220 210]
  [180 190 230]
  [240 280 300]]

 [[180 210 230]
  [250 270 260]
  [240 250 270]
  [290 310 330]]

 [[200 220 240]
  [260 280 300]
  [320 340 360]
  [380 400 420]]]
Ventas Transposed:
 [[150 180 200]
 [200 210 220]
 [250 230 240]
 [300 250 260]
 [220 270 280]
 [210 260 300]
 [180 240 320]
 [190 250 340]
 [230 270 360]
 [240 290 380]
 [280 310 400]
 [300 330 420]]
Ventas Invertidas:
 [[300 280 240 230 190 180 210 220 300 250 200 150]
 [330 310 290 270 250 240 260 270 250 230 210 180]
 [420 400 380 360 340 320 300 280 260 240 220 200]]
Ventas Aplanadas:
 [150 200 250 300 220 210 180 190 230 240 280 300 180 210 230 250 270 260
 240 250 270 290 310 330 200 220 240 260 280 300 320 340 360 380 400 420]


In [44]:
# Paso 5: Análisis de elementos únicos y sus conteos
unique_ventas, counts_ventas = np.unique(ventas_flattened, return_counts=True)
print("Elementos únicos en las ventas:", unique_ventas)
print("Conteos de elementos únicos en las ventas:", counts_ventas)

Elementos únicos en las ventas: [150 180 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340
 360 380 400 420]
Conteos de elementos únicos en las ventas: [1 2 1 2 2 2 2 3 3 2 2 2 1 3 1 1 1 1 1 1 1 1]


In [45]:
# Paso 6: Indexación y slicing
# Seleccionar ventas del primer trimestre
ventas_primer_trimestre = ventas_matrix[:, :3]
print("Ventas del primer trimestre:\n", ventas_primer_trimestre)

# Indexación booleana para seleccionar meses con ventas totales superiores a 800
meses_altas_ventas = meses[total_ventas_por_mes > 800]
ventas_altas = total_ventas_por_mes[total_ventas_por_mes > 800]
print("Meses con ventas totales superiores a 800:", meses_altas_ventas)
print("Ventas totales superiores a 800:", ventas_altas)

# Selección avanzada
indices = [0, 2, 4, 6, 8, 10]
ventas_indices_seleccionados = ventas_matrix[:, indices]
print("Ventas en meses seleccionados:\n", ventas_indices_seleccionados)

Ventas del primer trimestre:
 [[150 200 250]
 [180 210 230]
 [200 220 240]]
Meses con ventas totales superiores a 800: ['Abril' 'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']
Ventas totales superiores a 800: [ 810  860  910  990 1050]
Ventas en meses seleccionados:
 [[150 250 220 180 230 280]
 [180 230 270 240 270 310]
 [200 240 280 320 360 400]]
