# Dimensionalidad

In [1]:
import numpy as np
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [2]:
vector = np.array([30,29,35,31,33,36,42])
print(vector)

[30 29 35 31 33 36 42]


In [3]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
tensor = np.array([[[1,2],[3,4],[5,6], [7,8]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [5]:
array_arange = np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
eye_matrix = np.eye(6)
print(eye_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [7]:
diag = np.diag([1,2,3,4,5,6,7])
print(diag)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


In [8]:
random = np.random.random((2,3))
print(random)

[[0.03029375 0.25984727 0.3012193 ]
 [0.60754954 0.56423421 0.65044375]]
