# Indexación y Slicing

In [10]:
import numpy as np

array = np.array([10,20,30,40,50])
print(array[1])
print(array[-1])

20
50


In [11]:
print(array[1:4])

[20 30 40]


In [12]:
print(array[1:7])

[20 30 40 50]


In [13]:
print(array[-1:-7])

[]


In [14]:
array = np.array([10,20,30,40,50])
bool_index = array > 25
print(bool_index)
print(type(bool_index))

[False False  True  True  True]
<class 'numpy.ndarray'>


In [15]:
index = [2,0,3]
print(array[index])

[30 10 40]


In [16]:
array = np.random.randint(1, 10, size=(3,3))
print(array)
print(array[0,1])

[[8 6 4]
 [6 6 3]
 [9 6 5]]
6


In [17]:
print(array[:2,:2])

[[8 6]
 [6 6]]
